# Generated by Django 4.2 on 2025-04-07 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autores',
            name='data_nascimento',
            field=models.DateField(default='0'),
        ),
    ]
