# Generated by Django 5.2 on 2025-04-07 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='autor',
            field=models.CharField(default='0', max_length=255),
        ),
    ]
