# Generated by Django 5.2 on 2025-04-07 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0002_alter_autores_data_nascimento'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Livros',
            new_name='Livro',
        ),
    ]
