# Generated by Django 5.2 on 2025-04-07 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0003_alter_livro_isbn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livro',
            name='isbn',
        ),
    ]
