# Generated by Django 5.2 on 2025-04-07 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0004_remove_livro_isbn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='paginas',
            field=models.PositiveIntegerField(),
        ),
    ]
